[RobotPlotter]
font = cursive
char_height = 8
feed = 800
xmin = 0.0
xmax = 100.0
ymin = -50.0
ymax = 100.0
margin = 5.0
z_down = -3.0
z_up = 3.0
align = left
interline = 11.00
precision = 2
connection_type = Telnet
host = 192.168.0.1
port = 23
serial_port = /dev/pts/2
baudrate = 115200

